name: Publish to Github Packages

# add code to trigger the workflow manually
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Gradle Wrapper Validation
        # You may pin to the exact commit or the version.
        # uses: gradle/wrapper-validation-action@9ba54b687bf0f59b62abbf91e0d60de082e8ebc4
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: add permission
        run: chmod +x gradlew
          
      - name: Build with Gradle
        run: ./gradlew build

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v3
        
      - name: Publish to Github Packages
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
        if: success()
