name: Renovate
on:
  workflow_dispatch:
#  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
 #   - cron: '0/1 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      # - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.22
        with:
          renovate-version: 37.409.1
          configurationFile: renovate.json
          # docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
            LOG_LEVEL: 'debug'

