name: Versioning

# add code to trigger the workflow manually
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        
      - name: Git Version
  # You may pin to the exact commit or the version.
  # uses: codacy/git-version@fa06788276d7492a2af01662649696d249ecf4cb
        uses: codacy/git-version@2.4.0
        with:
    # The name of the release branch
          release-branch: main
  
  
